//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Son.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Asi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asi()
        {
            this.AsiStoks = new HashSet<AsiStok>();
            this.HastaAsis = new HashSet<HastaAsi>();
        }
        [DisplayName("Asi Adi:")]
        public int AsiId { get; set; }
        [DisplayName("Asi Adi:")]
        public string AsiAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsiStok> AsiStoks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaAsi> HastaAsis { get; set; }
    }
}
