//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Son.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsiTakipDBEntities : DbContext
    {
        public AsiTakipDBEntities()
            : base("name=AsiTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asi> Asis { get; set; }
        public virtual DbSet<AsiStok> AsiStoks { get; set; }
        public virtual DbSet<HastaAsi> HastaAsis { get; set; }
        public virtual DbSet<Hastalar> Hastalars { get; set; }
    }
}
