//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Son.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastalar()
        {
            this.HastaAsis = new HashSet<HastaAsi>();
        }
    
        public int HastaId { get; set; }
        [DisplayName("TC Kimlik No:")]
        public string TCNO { get; set; }
        [DisplayName("Ad:")]
        public string HastaAdi { get; set; }
        [DisplayName("Soyad:")]
        public string HastaSoyadi { get; set; }
        [DisplayName("Dogum Tarihi:")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> HastaDtar { get; set; }
        [DisplayName("Boy:")]
        public Nullable<int> HastaBoy { get; set; }
        [DisplayName("Kilo:")]
        public Nullable<int> HastaKilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaAsi> HastaAsis { get; set; }
    }
}
