//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Son.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaAsi
    {
        public int HastaAsiId { get; set; }
        public int HastaId { get; set; }
        public int AsiId { get; set; }
    
        public virtual Asi Asi { get; set; }
        public virtual Hastalar Hastalar { get; set; }
    }
}
